-- =====================================================================
-- V1 — Baseline du schéma Kola
--
-- Reproduit à l'identique le schéma que `ddl-auto=update` générait
-- jusqu'ici, index existants compris. Aucun changement fonctionnel :
-- c'est le point de départ à partir duquel les migrations suivantes
-- sont exprimées.
--
-- Si vous avez déjà une base créée par ddl-auto, ne rejouez pas ce
-- script : faites `flyway baseline` sur la version 1, puis appliquez
-- directement V2.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Identité et rôles
-- ---------------------------------------------------------------------
create table role (
    id                 integer generated by default as identity,
    role_name          varchar(255) unique,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table _user (
    id                      bigint generated by default as identity,
    first_name              varchar(255),
    last_name               varchar(255),
    email                   varchar(255) unique,
    phone_number            varchar(255) not null unique,
    country_code            varchar(2),
    avatar                  varchar(255),
    kyc_level               varchar(255) check (kyc_level in ('TIER_0','TIER_1','TIER_2','TIER_3')),
    password                varchar(255),
    enabled                 boolean not null,
    account_locked          boolean not null,
    failed_login_attempts   integer not null,
    locked_at               timestamp(6),
    last_known_ip           varchar(255),
    last_known_user_agent   varchar(255),
    created_at              timestamp(6) not null,
    last_modified_date      timestamp(6),
    primary key (id)
);

create table user_roles (
    user_id bigint  not null,
    role_id integer not null
);

-- ---------------------------------------------------------------------
-- Monnaie : portefeuilles, coffres, bénéficiaires
-- ---------------------------------------------------------------------
create table wallets (
    id                 bigint generated by default as identity,
    currency           varchar(3) not null,
    balance            numeric(19,4) not null,
    locked_balance     numeric(19,4) not null,
    active             boolean not null,
    version            bigint default 0 not null,
    owner_id           bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table vaults (
    id                 bigint generated by default as identity,
    name               varchar(255) not null,
    purpose            varchar(255),
    currency           varchar(3) not null,
    target_amount      numeric(19,4),
    current_amount     numeric(19,4) not null,
    unlock_date        date,
    status             varchar(255) not null check (status in ('ACTIVE','UNLOCKED','CLOSED')),
    version            bigint default 0 not null,
    owner_id           bigint not null,
    wallet_id          bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table beneficiaries (
    id                 bigint generated by default as identity,
    alias              varchar(255) not null,
    phone_number       varchar(255) not null,
    country_code       varchar(2) not null,
    network            varchar(255) not null check (network in ('MIXX_BY_YAS','MOOV_TOGO','WAVE','ORANGE_MONEY','FREE_MONEY','MTN_MOMO','VODAFONE_CASH','AIRTELTIGO','OPAY','PALMPAY','WESTERN_UNION','MONEYGRAM')),
    owner_id           bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table merchants (
    id                 bigint generated by default as identity,
    name               varchar(255) not null,
    category           varchar(255),
    merchant_code      varchar(255) not null unique,
    balance            numeric(19,4) not null,
    currency           varchar(3) not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------
-- Grand livre
-- ---------------------------------------------------------------------
create table transactions (
    id                    bigint generated by default as identity,
    reference             varchar(255) not null unique,
    type                  varchar(255) not null check (type in ('DEPOSIT','WITHDRAWAL','TRANSFER_OUT','TRANSFER_IN','VAULT_LOCK','VAULT_UNLOCK','FEE','SCHEDULED_TRANSFER','LOAN_DISBURSEMENT','LOAN_REPAYMENT','MERCHANT_PAYMENT')),
    status                varchar(255) not null check (status in ('PENDING','SUCCESS','FAILED','CANCELLED','REFUNDED')),
    amount                numeric(19,4) not null,
    fee                   numeric(19,4) not null,
    currency              varchar(3) not null,
    receiver_currency     varchar(3),
    exchange_rate         numeric(19,6),
    wallet_id             bigint,
    sender_id             bigint,
    receiver_id           bigint,
    receiver_phone_number varchar(255),
    receiver_country_code varchar(2),
    description           varchar(255),
    external_reference    varchar(255),
    idempotency_key       varchar(255) unique,
    created_at            timestamp(6) not null,
    last_modified_date    timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------
-- Crédit
-- ---------------------------------------------------------------------
create table credit_scores (
    id                 bigint generated by default as identity,
    score              integer not null,
    tier               varchar(255) not null check (tier in ('INELIGIBLE','BASIC','STANDARD','PREMIUM','ELITE')),
    breakdown_json     TEXT,
    max_loan_amount    numeric(15,2) not null,
    monthly_rate       numeric(5,4) not null,
    expires_at         timestamp(6) not null,
    latest             boolean not null,
    user_id            bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table loan_requests (
    id                 bigint generated by default as identity,
    requested_amount   numeric(15,2) not null,
    duration_months    integer not null,
    monthly_rate       numeric(5,4) not null,
    total_repayment    numeric(15,2) not null,
    status             varchar(255) not null check (status in ('PENDING','APPROVED','REJECTED','DISBURSED','REPAID','DEFAULTED')),
    purpose            varchar(255),
    due_date           date,
    rejection_reason   varchar(255),
    defaulted_at       timestamp(6),
    borrower_id        bigint not null,
    wallet_id          bigint not null,
    credit_score_id    bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------
-- Conformité, notifications, virements programmés, jetons
-- ---------------------------------------------------------------------
create table aml_alerts (
    id                   bigint generated by default as identity,
    risk_score           integer not null,
    risk_level           varchar(255) not null check (risk_level in ('LOW','MEDIUM','HIGH','CRITICAL')),
    status               varchar(255) not null check (status in ('OPEN','REVIEWING','CLEARED','CONFIRMED')),
    triggered_rules_json TEXT,
    review_notes         varchar(1000),
    reviewed_by          varchar(255),
    user_id              bigint not null,
    transaction_id       bigint,
    created_at           timestamp(6) not null,
    last_modified_date   timestamp(6),
    primary key (id)
);

create table notifications (
    id                 bigint generated by default as identity,
    title              varchar(255) not null,
    body               varchar(500) not null,
    type               varchar(255) not null check (type in ('TRANSACTION','SECURITY','SYSTEM')),
    read               boolean not null,
    user_id            bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

create table scheduled_transfers (
    id                  bigint generated by default as identity,
    frequency           varchar(255) not null check (frequency in ('MONTHLY','WEEKLY')),
    execution_day       integer not null,
    amount              numeric(19,4) not null,
    currency            varchar(3) not null,
    description         varchar(255),
    status              varchar(255) not null check (status in ('ACTIVE','PAUSED','FAILED_PERMANENTLY')),
    last_executed_at    timestamp(6),
    next_execution_date timestamp(6),
    user_id             bigint not null,
    wallet_id           bigint not null,
    target_vault_id     bigint,
    created_at          timestamp(6) not null,
    last_modified_date  timestamp(6),
    primary key (id)
);

create table token (
    id                 bigint generated by default as identity,
    token              varchar(6),
    token_type         varchar(255) check (token_type in ('ACTIVATION','PASSWORD_RESET')),
    expires_at         timestamp(6),
    validated_at       timestamp(6),
    user_id            bigint not null,
    created_at         timestamp(6) not null,
    last_modified_date timestamp(6),
    primary key (id)
);

-- ---------------------------------------------------------------------
-- Index déjà déclarés sur les entités
-- ---------------------------------------------------------------------
create index idx_aml_status_created  on aml_alerts    (status, created_at);
create index idx_aml_risk_level      on aml_alerts    (risk_level);
create index idx_aml_user            on aml_alerts    (user_id);
create index idx_credit_user_latest  on credit_scores (user_id, latest);
create index idx_notif_user_created  on notifications (user_id, created_at);
create index idx_notif_user_read     on notifications (user_id, read);
create index idx_tx_status_created   on transactions  (status, created_at);
create index idx_tx_type_currency    on transactions  (type, currency);
create index idx_tx_wallet_created   on transactions  (wallet_id, created_at);
create index idx_tx_idempotency_key  on transactions  (idempotency_key);

-- ---------------------------------------------------------------------
-- Clés étrangères
-- ---------------------------------------------------------------------
alter table user_roles          add constraint fk_user_roles_user      foreign key (user_id)         references _user;
alter table user_roles          add constraint fk_user_roles_role      foreign key (role_id)         references role;
alter table wallets             add constraint fk_wallets_owner        foreign key (owner_id)        references _user;
alter table vaults              add constraint fk_vaults_owner         foreign key (owner_id)        references _user;
alter table vaults              add constraint fk_vaults_wallet        foreign key (wallet_id)       references wallets;
alter table beneficiaries       add constraint fk_beneficiaries_owner  foreign key (owner_id)        references _user;
alter table transactions        add constraint fk_tx_wallet            foreign key (wallet_id)       references wallets;
alter table transactions        add constraint fk_tx_sender            foreign key (sender_id)       references _user;
alter table transactions        add constraint fk_tx_receiver          foreign key (receiver_id)     references _user;
alter table credit_scores       add constraint fk_credit_scores_user   foreign key (user_id)         references _user;
alter table loan_requests       add constraint fk_loan_borrower        foreign key (borrower_id)     references _user;
alter table loan_requests       add constraint fk_loan_wallet          foreign key (wallet_id)       references wallets;
alter table loan_requests       add constraint fk_loan_credit_score    foreign key (credit_score_id) references credit_scores;
alter table aml_alerts          add constraint fk_aml_user             foreign key (user_id)         references _user;
alter table aml_alerts          add constraint fk_aml_transaction      foreign key (transaction_id)  references transactions;
alter table notifications       add constraint fk_notifications_user   foreign key (user_id)         references _user;
alter table scheduled_transfers add constraint fk_sched_user           foreign key (user_id)         references _user;
alter table scheduled_transfers add constraint fk_sched_wallet         foreign key (wallet_id)       references wallets;
alter table scheduled_transfers add constraint fk_sched_target_vault   foreign key (target_vault_id) references vaults;
alter table token               add constraint fk_token_user           foreign key (user_id)         references _user;
