import { Ionicons } from '@expo/vector-icons';
import * as LocalAuthentication from 'expo-local-authentication';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Logo from '../components/Logo';
import { ApiError, authApi, AuthSession } from '../services/api';
import { c } from '../theme';

const digits=(value:string)=>value.replace(/\D/g,'').slice(0,4);

export default function AppLockScreen({session,onUnlock,onLogout}:{session:AuthSession;onUnlock:(session?:AuthSession)=>Promise<void>|void;onLogout:()=>Promise<void>|void}){
  const [pin,setPin]=useState(''),[loading,setLoading]=useState(false),[biometric,setBiometric]=useState(false),[biometricLabel,setBiometricLabel]=useState('Biométrie');
  useEffect(()=>{LocalAuthentication.hasHardwareAsync().then(async hardware=>{const enrolled=hardware&&await LocalAuthentication.isEnrolledAsync();setBiometric(enrolled);if(enrolled){const types=await LocalAuthentication.supportedAuthenticationTypesAsync();setBiometricLabel(types.includes(LocalAuthentication.AuthenticationType.FACIAL_RECOGNITION)?'Face ID':types.includes(LocalAuthentication.AuthenticationType.FINGERPRINT)?'Empreinte digitale':'Biométrie');}}).catch(()=>setBiometric(false));},[]);
  const unlockWithPin=async()=>{if(pin.length!==4){Alert.alert('PIN incomplet','Saisissez votre code PIN à 4 chiffres.');return;}setLoading(true);try{await onUnlock(await authApi.login(session.user.phone,pin));}catch(error){setPin('');Alert.alert('Accès refusé',error instanceof ApiError?error.message:'Impossible de vérifier le code PIN.');}finally{setLoading(false);}};
  const unlockWithBiometrics=async()=>{setLoading(true);try{const result=await LocalAuthentication.authenticateAsync({promptMessage:'Déverrouiller KOLA',cancelLabel:'Utiliser le code PIN',fallbackLabel:'Utiliser le code du téléphone',disableDeviceFallback:false});if(result.success)await onUnlock();}catch{Alert.alert('Biométrie indisponible','Utilisez votre code PIN KOLA.');}finally{setLoading(false);}};
  return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.page} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.brand}><Logo width={125}/><Text style={s.hello}>Bonjour {session.user.firstName}</Text><Text style={s.subtitle}>Déverrouillez KOLA pour accéder à votre compte.</Text></View><View style={s.lock}><View style={s.icon}><Ionicons name="lock-closed" size={28} color={c.yellow}/></View><Text style={s.label}>CODE PIN</Text><View style={s.pinWrap}><Ionicons name="keypad-outline" size={20} color={c.muted}/><TextInput autoFocus value={pin} onChangeText={value=>setPin(digits(value))} onSubmitEditing={unlockWithPin} secureTextEntry keyboardType="number-pad" maxLength={4} placeholder="••••" placeholderTextColor={c.muted} style={s.pin}/></View><TouchableOpacity disabled={loading} onPress={unlockWithPin} style={[s.primary,loading&&s.disabled]}>{loading?<ActivityIndicator color={c.primary}/>:<Text style={s.primaryText}>Déverrouiller</Text>}</TouchableOpacity>{biometric&&<TouchableOpacity disabled={loading} onPress={unlockWithBiometrics} style={s.biometric}><Ionicons name="finger-print" size={25} color={c.primary}/><Text style={s.biometricText}>Utiliser {biometricLabel}</Text></TouchableOpacity>}</View><TouchableOpacity onPress={onLogout} style={s.logout}><Text style={s.logoutText}>Changer de compte</Text></TouchableOpacity></KeyboardAvoidingView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:c.bg},page:{flex:1,paddingHorizontal:24},brand:{alignItems:'center',paddingTop:52},hello:{fontSize:27,fontWeight:'900',color:c.ink,marginTop:35},subtitle:{fontSize:11,lineHeight:17,color:c.muted,textAlign:'center',marginTop:7},lock:{marginTop:38,borderRadius:22,backgroundColor:c.white,borderWidth:1,borderColor:c.border,padding:20},icon:{width:58,height:58,borderRadius:29,backgroundColor:c.primary,alignItems:'center',justifyContent:'center',alignSelf:'center',marginTop:-49},label:{fontSize:9,fontWeight:'800',color:c.muted,marginTop:24,marginBottom:7},pinWrap:{height:56,borderRadius:13,borderWidth:1,borderColor:c.border,flexDirection:'row',alignItems:'center',paddingHorizontal:14,gap:10},pin:{flex:1,fontSize:24,fontWeight:'900',letterSpacing:12,color:c.primary,textAlign:'center'},primary:{height:52,borderRadius:26,backgroundColor:c.yellow,alignItems:'center',justifyContent:'center',marginTop:17},primaryText:{fontSize:13,fontWeight:'900',color:c.primary},disabled:{opacity:.65},biometric:{height:50,borderRadius:25,borderWidth:1,borderColor:c.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:10},biometricText:{fontSize:12,fontWeight:'800',color:c.primary},logout:{alignSelf:'center',padding:15,marginTop:12},logoutText:{fontSize:11,fontWeight:'700',color:c.muted}});
