import { createAudioPlayer, setAudioModeAsync } from 'expo-audio';
import * as FileSystem from 'expo-file-system/legacy';
import * as Haptics from 'expo-haptics';

const sounds={
  sending:'UklGRmQBAABXQVZFZm10IBAAAAABAAEAoA8AAKAPAAABAAgAZGF0YUABAACAgICAgICAgICAgICAgICAZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62gICAgICAgICAgICAgICAgICAgICAgICAgA==',
  success:'UklGRvQCAABXQVZFZm10IBAAAAABAAEAoA8AAKAPAAABAAgAZGF0YdACAACAgICAgICAgICAgICAgICAh1dLbaC3nWpKWYqyroJUTHKkt5lmSV2PtKt9UU53qLaUYUlhlLaod05Rfau0j11JZpm3pHJMVIKusopZSmqdt6BtS1eHsbCFVktvorecaUpajLOtgFNNdKa2l2RJXpG1qntQT3mptZNgSWOWtqd2TlJ+rLSOXElnmrejcUxVg6+yiVhKbJ+3n2xKWImyr4NVTHGjt5pnSVyOtKx+Uk52p7aWY0lgTo63h0xmqqpmTIe3jk5gpq5sSoC2lFJaoLJySXm0mlZWmrR5SXKyoFpSlLaASmyupmBOjreHTGaqqmZMh7eOTmCmrmxKgLaUUlqgsnJJebSaVlaatHlJcrKgWlKUtoBKbK6mYE6Ot4dMZqqqZkyHt45OYKaubEqAtpRSWqCyckl5tJpWVpq0eUlysqBaUpS2gEpsrqZgTo63h0xmqqpmTIe3jk5gpq5sSoC2lFJaoLJySXm0mlZWmrR5SXKyoFpSlLaASmyupmBOjreHTGaqqmZMh7eOTmCmrmxKgLaUUlqgsnJJebSaVlaatHlJcrKgWlKUtoBKbK6mYE6Ot4dMZqqqZkyHt45OYKaubEqAtpRSWqCyckl5tJpWVpq0eUlysqBaUpS2gEpsrqZgTo63h0xmqqpmTIe3jk5gpq5sSoC2lFJaoLJySXm0mlZWmrR5SXKyoFpSlLaASmyupmBOjreHTGaqqmZMh7eOTmCmrmxKgLaUUlqgsnJJebSaVlaatHlJcrKgWlKUtoBKbK6mYE6Ot4dMZqqqZkyHt45OYKaubEqAtpRSWqCyckl5tJpWVpq0eUlysqBaUpS2gEpsrqZgTo63h0xmqqpmTIe3jk5gpq5sSoC2lFJaoLJySXm0mlZWmrR5SXKyoFpSlLaASmyupmBOjreHTGaqqmZMh7eOToCAgICAgICAgICAgICAgICAgICAgICAgIA=',
  failure:'UklGRmQBAABXQVZFZm10IBAAAAABAAEAoA8AAKAPAAABAAgAZGF0YUABAACAgICAgICAgICAgICAgICAZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62oHlWSVqApreqh2BKUnKatLKUbE5MZo6utqB5VklagKa3qodgSlJymrSylGxOTGaOrrageVZJWoCmt6qHYEpScpq0spRsTkxmjq62gICAgICAgICAgICAgICAgICAgICAgICAgA==',
};

export async function playTransactionSound(kind:keyof typeof sounds){
  try{
    if(kind==='success')await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);else if(kind==='failure')await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);else await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    await setAudioModeAsync({playsInSilentMode:true});
    if(!FileSystem.cacheDirectory)return;
    const uri=`${FileSystem.cacheDirectory}kola-${kind}.wav`;
    await FileSystem.writeAsStringAsync(uri,sounds[kind],{encoding:FileSystem.EncodingType.Base64});
    const player=createAudioPlayer(uri);player.volume=.75;player.play();setTimeout(()=>player.remove(),1400);
  }catch{}
}
