import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { c } from '../theme';

type Mode='welcome'|'login'|'signup';
export default function AuthScreen({onAuthenticated}:{onAuthenticated:()=>void}){
 const [mode,setMode]=useState<Mode>('welcome'),[name,setName]=useState(''),[phone,setPhone]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[secure,setSecure]=useState(true),[accepted,setAccepted]=useState(false);
 const submit=()=>{if(phone.replace(/\D/g,'').length<8||password.length<6){Alert.alert('Informations incomplètes','Saisissez un numéro valide et un mot de passe de 6 caractères minimum.');return;}if(mode==='signup'&&(!name.trim()||!email.includes('@')||password!==confirm||!accepted)){Alert.alert('Création impossible','Vérifiez le nom, l’e-mail, la confirmation du mot de passe et les conditions.');return;}onAuthenticated();};
 if(mode==='welcome')return <SafeAreaView style={s.safe}><View style={s.welcome}><View style={s.logo}><Text style={s.logoLetter}>D</Text></View><Text style={s.brand}>DOGAA</Text><Text style={s.welcomeTitle}>Votre finance.{`\n`}Votre avenir.</Text><Text style={s.welcomeText}>Un portefeuille sécurisé pour payer, épargner et construire votre accès au crédit.</Text><View style={s.actions}><TouchableOpacity onPress={()=>setMode('signup')} style={s.primary}><Text style={s.primaryText}>Créer mon compte</Text><Ionicons name="arrow-forward" size={19} color={c.primary}/></TouchableOpacity><TouchableOpacity onPress={()=>setMode('login')} style={s.secondary}><Text style={s.secondaryText}>J’ai déjà un compte</Text></TouchableOpacity></View><View style={s.secureLine}><Ionicons name="shield-checkmark-outline" size={16} color={c.green}/><Text style={s.secureText}>Protection des données et sécurité DOGAA</Text></View></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.formPage} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={()=>setMode('welcome')} style={s.back}><Ionicons name="arrow-back" size={20} color={c.primary}/></TouchableOpacity><View style={s.formIcon}><Ionicons name={mode==='signup'?'person-add-outline':'log-in-outline'} size={25} color={c.yellow}/></View><Text style={s.formTitle}>{mode==='signup'?'Créer un compte':'Bon retour parmi nous'}</Text><Text style={s.formSub}>{mode==='signup'?'Rejoignez DOGAA en quelques étapes.':'Connectez-vous à votre portefeuille DOGAA.'}</Text>{mode==='signup'&&<><Label text="NOM COMPLET"/><Field value={name} onChangeText={setName} placeholder="Votre nom et prénom" icon="person-outline"/><Label text="ADRESSE E-MAIL"/><Field value={email} onChangeText={setEmail} placeholder="nom@exemple.com" icon="mail-outline" keyboardType="email-address"/></>}<Label text="NUMÉRO DE TÉLÉPHONE"/><Field value={phone} onChangeText={setPhone} placeholder="+225 07 00 00 00 00" icon="call-outline" keyboardType="phone-pad"/><Label text="MOT DE PASSE"/><View style={s.inputWrap}><Ionicons name="lock-closed-outline" size={18} color={c.muted}/><TextInput value={password} onChangeText={setPassword} placeholder="6 caractères minimum" placeholderTextColor={c.muted} secureTextEntry={secure} style={s.input}/><TouchableOpacity onPress={()=>setSecure(v=>!v)}><Ionicons name={secure?'eye-outline':'eye-off-outline'} size={20} color={c.muted}/></TouchableOpacity></View>{mode==='signup'&&<><Label text="CONFIRMER LE MOT DE PASSE"/><Field value={confirm} onChangeText={setConfirm} placeholder="Saisissez à nouveau" icon="shield-checkmark-outline" secureTextEntry/><TouchableOpacity onPress={()=>setAccepted(v=>!v)} style={s.consent}><Ionicons name={accepted?'checkbox':'square-outline'} size={22} color={accepted?c.greenDark:c.muted}/><Text style={s.consentText}>J’accepte les conditions d’utilisation et la politique de confidentialité.</Text></TouchableOpacity></>}<TouchableOpacity onPress={submit} style={s.primary}><Text style={s.primaryText}>{mode==='signup'?'Créer mon compte':'Se connecter'}</Text><Ionicons name="arrow-forward" size={19} color={c.primary}/></TouchableOpacity><TouchableOpacity onPress={()=>setMode(mode==='signup'?'login':'signup')}><Text style={s.switch}>{mode==='signup'?'Vous avez déjà un compte ? Se connecter':'Nouveau sur DOGAA ? Créer un compte'}</Text></TouchableOpacity>{mode==='login'&&<TouchableOpacity><Text style={s.forgot}>Mot de passe oublié ?</Text></TouchableOpacity>}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
function Label({text}:{text:string}){return <Text style={s.label}>{text}</Text>}
function Field(props:React.ComponentProps<typeof TextInput>&{icon:React.ComponentProps<typeof Ionicons>['name']}){const {icon,...input}=props;return <View style={s.inputWrap}><Ionicons name={icon} size={18} color={c.muted}/><TextInput {...input} placeholderTextColor={c.muted} autoCapitalize="none" style={s.input}/></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:c.bg},welcome:{flex:1,paddingHorizontal:25,paddingTop:70},logo:{width:64,height:64,borderRadius:19,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},logoLetter:{fontSize:34,fontWeight:'900',color:c.yellow},brand:{fontSize:18,fontWeight:'900',letterSpacing:1,color:c.primary,marginTop:10},welcomeTitle:{fontSize:38,lineHeight:45,fontWeight:'900',color:c.ink,marginTop:55},welcomeText:{fontSize:13,lineHeight:21,color:c.muted,marginTop:14,maxWidth:330},actions:{marginTop:'auto',gap:10},primary:{minHeight:54,borderRadius:27,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,paddingHorizontal:18},primaryText:{fontSize:14,fontWeight:'900',color:c.primary},secondary:{height:52,borderRadius:26,borderWidth:1.5,borderColor:c.primary,alignItems:'center',justifyContent:'center'},secondaryText:{fontSize:13,fontWeight:'800',color:c.primary},secureLine:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,marginVertical:22},secureText:{fontSize:8,color:c.muted},formPage:{paddingHorizontal:22,paddingTop:14,paddingBottom:35},back:{width:40,height:40,borderRadius:20,backgroundColor:c.pale2,alignItems:'center',justifyContent:'center'},formIcon:{width:52,height:52,borderRadius:16,backgroundColor:c.primary,alignItems:'center',justifyContent:'center',marginTop:21},formTitle:{fontSize:27,fontWeight:'900',color:c.ink,marginTop:13},formSub:{fontSize:11,color:c.muted,marginTop:4,marginBottom:8},label:{fontSize:8,fontWeight:'800',color:c.muted,marginTop:14,marginBottom:6},inputWrap:{height:48,borderRadius:12,borderWidth:1,borderColor:c.border,backgroundColor:c.white,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12},input:{flex:1,fontSize:11,color:c.ink},consent:{flexDirection:'row',alignItems:'flex-start',gap:8,marginVertical:15},consentText:{fontSize:9,lineHeight:14,color:c.muted,flex:1},switch:{fontSize:10,fontWeight:'700',color:c.primary,textAlign:'center',marginTop:18},forgot:{fontSize:10,color:c.muted,textAlign:'center',marginTop:13}});
