import { Ionicons } from '@expo/vector-icons';
import * as DocumentPicker from 'expo-document-picker';
import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card, Progress, Screen } from '../components/Layout';
import { c } from '../theme';
import { Route } from '../types';

type DocKey='identityFront'|'identityBack'|'address';
type SelectedDoc={name:string;size?:number;mimeType?:string;uri:string};
const requirements:{key:DocKey;title:string;sub:string;icon:React.ComponentProps<typeof Ionicons>['name']}[]=[
  {key:'identityFront',title:'Pièce d’identité — recto',sub:'CNI, passeport ou titre de séjour',icon:'id-card-outline'},
  {key:'identityBack',title:'Pièce d’identité — verso',sub:'Face arrière lisible et complète',icon:'copy-outline'},
  {key:'address',title:'Justificatif de domicile',sub:'Facture récente de moins de 3 mois',icon:'home-outline'},
];

export default function KycScreen({navigate}:{navigate:(r:Route)=>void}){
  const [docs,setDocs]=useState<Partial<Record<DocKey,SelectedDoc>>>({});
  const [consent,setConsent]=useState(false),[submitted,setSubmitted]=useState(false);
  const count=Object.keys(docs).length;
  const pick=async(key:DocKey)=>{try{const result=await DocumentPicker.getDocumentAsync({type:['image/jpeg','image/png','application/pdf'],copyToCacheDirectory:true,multiple:false});if(result.canceled)return;const asset=result.assets[0];if(asset.size&&asset.size>10*1024*1024){Alert.alert('Fichier trop volumineux','Le document doit faire moins de 10 Mo.');return;}setDocs(current=>({...current,[key]:{name:asset.name,size:asset.size,mimeType:asset.mimeType,uri:asset.uri}}));}catch{Alert.alert('Import impossible','Le document n’a pas pu être ouvert. Réessayez.');}};
  const submit=()=>{if(count<3){Alert.alert('Dossier incomplet','Ajoutez les trois documents demandés.');return;}if(!consent){Alert.alert('Consentement requis','Confirmez que les documents sont exacts et vous appartiennent.');return;}setSubmitted(true);};
  if(submitted)return <Screen route="kyc" navigate={navigate}><View style={s.success}><View style={s.successIcon}><Ionicons name="hourglass-outline" size={38} color={c.white}/></View><Text style={s.successTitle}>Dossier KYC envoyé</Text><Text style={s.successText}>Vos documents sont prêts pour la vérification. Vous recevrez une notification dès que l’examen sera terminé.</Text><View style={s.review}><Ionicons name="time-outline" size={18} color={c.primary}/><Text style={s.reviewText}>Délai estimé : moins de 24 heures</Text></View><TouchableOpacity onPress={()=>navigate('profile')} style={s.primary}><Text style={s.primaryText}>Retour au profil</Text></TouchableOpacity></View></Screen>;
  return <Screen route="kyc" navigate={navigate}>
    <TouchableOpacity onPress={()=>navigate('profile')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Mon profil</Text></TouchableOpacity>
    <View style={s.head}><View><Text style={s.overline}>VÉRIFICATION D’IDENTITÉ</Text><Text style={s.title}>Passer le KYC</Text><Text style={s.subtitle}>Complétez votre dossier pour accéder au TIER 3.</Text></View><View style={s.shield}><Ionicons name="shield-checkmark-outline" size={25} color={c.yellow}/></View></View>
    <Card style={s.progressCard}><View style={s.progressTop}><Text style={s.progressTitle}>Votre dossier</Text><Text style={s.progressValue}>{count}/3 documents</Text></View><Progress value={count/3*100} color={c.green}/><Text style={s.progressHint}>Formats acceptés : JPG, PNG ou PDF • 10 Mo maximum</Text></Card>
    <View style={s.security}><Ionicons name="lock-closed-outline" size={18} color={c.greenDark}/><Text style={s.securityText}>Vos documents sont confidentiels et seront transmis de façon chiffrée au service de vérification DOGAA.</Text></View>
    <Text style={s.sectionTitle}>Documents personnels</Text>
    {requirements.map(item=>{const doc=docs[item.key];return <Card key={item.key} style={[s.document,!!doc&&s.documentReady]}><View style={s.docTop}><View style={[s.docIcon,!!doc&&s.docIconReady]}><Ionicons name={doc?'checkmark':item.icon} size={22} color={doc?c.white:c.primary}/></View><View style={s.docCopy}><Text style={s.docTitle}>{item.title}</Text><Text style={s.docSub} numberOfLines={2}>{doc?doc.name:item.sub}</Text>{doc?.size&&<Text style={s.docSize}>{(doc.size/1024/1024).toFixed(1)} Mo</Text>}</View></View><TouchableOpacity onPress={()=>pick(item.key)} style={[s.upload,!!doc&&s.replace]}><Ionicons name={doc?'refresh-outline':'cloud-upload-outline'} size={18} color={doc?c.primary:c.white}/><Text style={[s.uploadText,!!doc&&s.replaceText]}>{doc?'Remplacer':'Choisir un fichier'}</Text></TouchableOpacity></Card>})}
    <TouchableOpacity onPress={()=>setConsent(v=>!v)} style={s.consent}><Ionicons name={consent?'checkbox':'square-outline'} size={23} color={consent?c.greenDark:c.muted}/><Text style={s.consentText}>Je certifie que ces documents sont valides, lisibles et m’appartiennent.</Text></TouchableOpacity>
    <TouchableOpacity onPress={submit} style={[s.primary,count<3&&s.primaryDisabled]}><Ionicons name="shield-checkmark-outline" size={20} color={c.primary}/><Text style={s.primaryText}>Envoyer mon dossier KYC</Text></TouchableOpacity><Text style={s.legal}>Aucun document ne sera publié ou partagé à des fins commerciales.</Text>
  </Screen>;
}

const s=StyleSheet.create({back:{height:36,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,marginTop:8},overline:{fontSize:8,fontWeight:'800',color:c.greenDark},title:{fontSize:25,fontWeight:'900',color:c.ink,marginTop:2},subtitle:{fontSize:10,lineHeight:14,color:c.muted,marginTop:3,maxWidth:260},shield:{width:50,height:50,borderRadius:15,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},progressCard:{marginTop:17},progressTop:{flexDirection:'row',justifyContent:'space-between',marginBottom:10},progressTitle:{fontSize:13,fontWeight:'800',color:c.ink},progressValue:{fontSize:10,fontWeight:'700',color:c.greenDark},progressHint:{fontSize:8,color:c.muted,marginTop:8},security:{flexDirection:'row',alignItems:'flex-start',gap:8,backgroundColor:'#DDFBED',borderRadius:11,padding:12,marginTop:10},securityText:{fontSize:9,lineHeight:13,color:c.greenDark,flex:1},sectionTitle:{fontSize:18,fontWeight:'800',color:c.ink,marginTop:23,marginBottom:10},document:{marginBottom:9,padding:13},documentReady:{borderColor:c.green},docTop:{flexDirection:'row',alignItems:'center',gap:10},docIcon:{width:42,height:42,borderRadius:13,backgroundColor:c.pale2,alignItems:'center',justifyContent:'center'},docIconReady:{backgroundColor:c.green},docCopy:{flex:1,minWidth:0},docTitle:{fontSize:12,fontWeight:'800',color:c.ink},docSub:{fontSize:9,lineHeight:12,color:c.muted,marginTop:2},docSize:{fontSize:8,color:c.greenDark,marginTop:3},upload:{height:39,borderRadius:20,backgroundColor:c.primary,marginTop:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},uploadText:{fontSize:10,fontWeight:'800',color:c.white},replace:{backgroundColor:c.pale2},replaceText:{color:c.primary},consent:{flexDirection:'row',alignItems:'flex-start',gap:9,paddingVertical:13},consentText:{fontSize:10,lineHeight:15,color:c.ink,flex:1},primary:{minHeight:52,borderRadius:27,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,paddingHorizontal:15},primaryDisabled:{opacity:.55},primaryText:{fontSize:13,fontWeight:'900',color:c.primary},legal:{fontSize:8,lineHeight:12,color:c.muted,textAlign:'center',marginTop:9,paddingHorizontal:12},success:{alignItems:'center',paddingTop:45},successIcon:{width:82,height:82,borderRadius:41,backgroundColor:c.green,alignItems:'center',justifyContent:'center'},successTitle:{fontSize:23,fontWeight:'900',color:c.ink,marginTop:20},successText:{fontSize:11,lineHeight:17,color:c.muted,textAlign:'center',marginTop:8,maxWidth:310},review:{flexDirection:'row',alignItems:'center',gap:7,backgroundColor:c.pale2,borderRadius:12,padding:13,marginVertical:24},reviewText:{fontSize:10,fontWeight:'700',color:c.primary}});
