import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card, Pill, Progress, Screen } from '../components/Layout';
import { c } from '../theme';
import { Route } from '../types';

const payments=[{date:'15 septembre 2026',amount:'36 000 FCFA',status:'Payé'},{date:'15 octobre 2026',amount:'36 000 FCFA',status:'À venir'},{date:'15 novembre 2026',amount:'36 000 FCFA',status:'À venir'}];
export default function LoanDetailScreen({navigate}:{navigate:(r:Route)=>void}){return <Screen route="loanDetail" navigate={navigate}>
  <TouchableOpacity onPress={()=>navigate('credit')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Mes crédits</Text></TouchableOpacity>
  <View style={s.head}><View><Text style={s.overline}>DÉTAIL DU PRÊT</Text><Text style={s.title}>Prêt activité commerciale</Text><Text style={s.reference}>Référence DOGAA-CR-2026-0412</Text></View><Pill green>À jour</Pill></View>
  <View style={s.hero}><Text style={s.heroLabel}>CAPITAL RESTANT</Text><Text style={s.heroAmount}>108 000 <Text style={s.fcfa}>FCFA</Text></Text><View style={s.progressHead}><Text style={s.heroSub}>42 000 FCFA déjà remboursés</Text><Text style={s.heroSub}>28%</Text></View><Progress value={28} color={c.yellow}/></View>
  <Card style={s.info}><Row icon="cash-outline" label="Montant emprunté" value="150 000 FCFA"/><Row icon="calculator-outline" label="Intérêts totaux" value="8% • 12 000 FCFA"/><Row icon="time-outline" label="Durée" value="5 mois"/><Row icon="calendar-outline" label="Prochaine échéance" value="15 oct. 2026"/><Row icon="wallet-outline" label="Mensualité" value="36 000 FCFA" last/></Card>
  <Text style={s.sectionTitle}>Échéancier</Text><Card style={s.schedule}>{payments.map((payment,index)=><View key={payment.date} style={[s.payment,index>0&&s.border]}><View style={[s.paymentIcon,payment.status==='Payé'&&s.paymentDone]}><Ionicons name={payment.status==='Payé'?'checkmark':'calendar-outline'} size={16} color={payment.status==='Payé'?c.white:c.primary}/></View><View style={s.paymentCopy}><Text style={s.paymentDate}>{payment.date}</Text><Text style={s.paymentStatus}>{payment.status}</Text></View><Text style={s.paymentAmount}>{payment.amount}</Text></View>)}</Card>
  <TouchableOpacity style={s.pay}><Ionicons name="card-outline" size={20} color={c.primary}/><Text style={s.payText}>Rembourser une échéance</Text></TouchableOpacity>
  <TouchableOpacity style={s.help}><Ionicons name="chatbubble-ellipses-outline" size={18} color={c.primary}/><Text style={s.helpText}>Besoin d’aide pour ce prêt ?</Text><Ionicons name="chevron-forward" size={17} color={c.primary}/></TouchableOpacity>
 </Screen>}
function Row({icon,label,value,last=false}:{icon:React.ComponentProps<typeof Ionicons>['name'];label:string;value:string;last?:boolean}){return <View style={[s.row,!last&&s.border]}><Ionicons name={icon} size={17} color={c.primary}/><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}
const s=StyleSheet.create({back:{height:36,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10,marginTop:8},overline:{fontSize:8,fontWeight:'800',color:c.greenDark},title:{fontSize:20,lineHeight:26,fontWeight:'900',color:c.ink,maxWidth:270},reference:{fontSize:8,color:c.muted,marginTop:3},hero:{backgroundColor:c.primary,borderRadius:14,padding:18,marginTop:17},heroLabel:{fontSize:8,fontWeight:'700',color:'#ADC6FF'},heroAmount:{fontSize:28,fontWeight:'900',color:c.yellow,marginVertical:5},fcfa:{fontSize:12,color:c.white},progressHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:9},heroSub:{fontSize:8,color:c.white},info:{marginTop:14,paddingVertical:5},row:{minHeight:48,flexDirection:'row',alignItems:'center',gap:8},border:{borderTopWidth:1,borderTopColor:c.border},rowLabel:{fontSize:10,color:c.muted,flex:1},rowValue:{fontSize:10,fontWeight:'800',color:c.ink,textAlign:'right',maxWidth:'45%'},sectionTitle:{fontSize:17,fontWeight:'800',color:c.ink,marginTop:23,marginBottom:10},schedule:{paddingVertical:2},payment:{minHeight:61,flexDirection:'row',alignItems:'center',gap:9},paymentIcon:{width:32,height:32,borderRadius:16,backgroundColor:c.pale2,alignItems:'center',justifyContent:'center'},paymentDone:{backgroundColor:c.green},paymentCopy:{flex:1},paymentDate:{fontSize:10,fontWeight:'700',color:c.ink},paymentStatus:{fontSize:8,color:c.muted,marginTop:2},paymentAmount:{fontSize:10,fontWeight:'800',color:c.primary},pay:{height:52,borderRadius:26,backgroundColor:c.yellow,marginTop:16,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},payText:{fontSize:12,fontWeight:'800',color:c.primary},help:{height:50,marginTop:9,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:12},helpText:{fontSize:10,fontWeight:'700',color:c.primary,flex:1}});
