import { Ionicons } from '@expo/vector-icons';
import React, { useRef, useState } from 'react';
import { Image, NativeScrollEvent, NativeSyntheticEvent, ScrollView, StyleSheet, Text, TouchableOpacity, useWindowDimensions, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { c } from '../theme';

const slides=[
  {image:require('../../assets/onboarding/financial-challenges.png'),eyebrow:'UNE RÉALITÉ QUOTIDIENNE',title:'Votre argent mérite mieux que la dispersion',text:'Paiements, espèces, factures et épargne sont difficiles à suivre quand tout est séparé.'},
  {image:require('../../assets/onboarding/connected-network.png'),eyebrow:'UN SEUL RÉSEAU',title:'Payez et recevez simplement',text:'DOGAA réunit particuliers, marchands et Mobile Money dans une expérience sécurisée.'},
  {image:require('../../assets/onboarding/smart-savings.png'),eyebrow:'VOS OBJECTIFS',title:'Épargnez à votre rythme',text:'Créez des coffres, programmez vos versements et avancez vers chaque projet.'},
  {image:require('../../assets/onboarding/fair-credit.png'),eyebrow:'VOTRE PROGRESSION',title:'Construisez votre accès au crédit',text:'Vos bonnes habitudes renforcent votre score et ouvrent des offres adaptées.'},
];
export default function OnboardingScreen({onFinish}:{onFinish:()=>void}){
  const {width,height}=useWindowDimensions();const [index,setIndex]=useState(0);const ref=useRef<ScrollView>(null);
  const next=()=>{if(index===slides.length-1){onFinish();return;}ref.current?.scrollTo({x:width*(index+1),animated:true});};
  const onScrollEnd=(event:NativeSyntheticEvent<NativeScrollEvent>)=>setIndex(Math.round(event.nativeEvent.contentOffset.x/width));
  return <SafeAreaView style={s.safe}><View style={s.top}><View style={s.brandMark}><Text style={s.brandLetter}>D</Text></View><Text style={s.brand}>DOGAA</Text><TouchableOpacity onPress={onFinish}><Text style={s.skip}>Passer</Text></TouchableOpacity></View><ScrollView ref={ref} horizontal pagingEnabled showsHorizontalScrollIndicator={false} onMomentumScrollEnd={onScrollEnd}>{slides.map((slide,i)=><View key={slide.title} style={[s.slide,{width}]}><View style={[s.imageWrap,{height:Math.min(height*.48,430)}]}><Image source={slide.image} style={s.image} resizeMode="contain"/></View><Text style={s.eyebrow}>{slide.eyebrow}</Text><Text style={s.title}>{slide.title}</Text><Text style={s.text}>{slide.text}</Text></View>)}</ScrollView><View style={s.bottom}><View style={s.dots}>{slides.map((_,i)=><View key={i} style={[s.dot,i===index&&s.dotActive]}/>)}</View><TouchableOpacity onPress={next} style={s.next}><Text style={s.nextText}>{index===slides.length-1?'Commencer':'Continuer'}</Text><Ionicons name={index===slides.length-1?'checkmark':'arrow-forward'} size={20} color={c.primary}/></TouchableOpacity></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:c.bg},top:{height:58,paddingHorizontal:20,flexDirection:'row',alignItems:'center'},brandMark:{width:24,height:24,borderRadius:7,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},brandLetter:{fontSize:13,fontWeight:'900',color:c.yellow},brand:{fontSize:17,fontWeight:'900',color:c.primary,marginLeft:8,flex:1},skip:{fontSize:11,fontWeight:'700',color:c.muted},slide:{alignItems:'center',paddingHorizontal:27},imageWrap:{width:'100%',alignItems:'center',justifyContent:'center'},image:{width:'100%',height:'100%'},eyebrow:{fontSize:9,fontWeight:'900',letterSpacing:1.1,color:c.greenDark,marginTop:7},title:{fontSize:25,lineHeight:32,fontWeight:'900',color:c.ink,textAlign:'center',marginTop:8,maxWidth:340},text:{fontSize:12,lineHeight:19,color:c.muted,textAlign:'center',marginTop:9,maxWidth:330},bottom:{paddingHorizontal:20,paddingBottom:18},dots:{height:26,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},dot:{width:7,height:7,borderRadius:4,backgroundColor:c.pale2},dotActive:{width:24,backgroundColor:c.primary},next:{height:54,borderRadius:27,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9},nextText:{fontSize:14,fontWeight:'900',color:c.primary}});
