import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import DatePickerField from '../components/DatePickerField';
import { Card, Screen } from '../components/Layout';
import { useDogaaData } from '../context/DogaaDataContext';
import { Biller, schedulingApi } from '../services/api';
import { c } from '../theme';
import { Route } from '../types';

const utilities:Biller[]=[
  {code:'ceet',displayName:'CEET — électricité',identifierLabel:'Référence client',identifierKind:'ALPHANUMERIC',minLength:4,maxLength:24,fixedAmount:false},
  {code:'cash_power',displayName:'Cash Power',identifierLabel:'Numéro du compteur',identifierKind:'DIGITS',minLength:6,maxLength:20,fixedAmount:false},
  {code:'tde',displayName:'TdE — eau',identifierLabel:'Référence client',identifierKind:'ALPHANUMERIC',minLength:4,maxLength:24,fixedAmount:false},
];
const money=(value:number)=>new Intl.NumberFormat('fr-FR').format(value);
const nextMonth=()=>{const date=new Date();date.setMonth(date.getMonth()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};
const tomorrow=()=>{const date=new Date();date.setDate(date.getDate()+1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};

export default function ServicePaymentsScreen({navigate,mode,onOpenSubscription}:{navigate:(route:Route)=>void;mode:'bills'|'subscriptions';onOpenSubscription?:(id:string)=>void}){
  const dogaa=useDogaaData(),isSubscription=mode==='subscriptions';
  const [remoteBillers,setRemoteBillers]=useState<Biller[]>([]),[selectedCode,setSelectedCode]=useState(''),[reference,setReference]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(isSubscription?nextMonth():tomorrow()),[fundingVaultId,setFundingVaultId]=useState(''),[automatic,setAutomatic]=useState(isSubscription),[saving,setSaving]=useState(false);
  useEffect(()=>{if(isSubscription)schedulingApi.billers().then(items=>{setRemoteBillers(items);if(items[0])setSelectedCode(current=>current||items[0].code);}).catch(error=>Alert.alert('Services indisponibles',error instanceof Error?error.message:'Impossible de charger les abonnements.'));else setSelectedCode(utilities[0].code);},[isSubscription]);
  useEffect(()=>{if(!fundingVaultId&&dogaa.vaults[0])setFundingVaultId(dogaa.vaults[0].id);},[dogaa.vaults,fundingVaultId]);
  const services=isSubscription?remoteBillers:utilities;
  const selected=services.find(item=>item.code===selectedCode)||services[0];
  const saved=useMemo(()=>dogaa.scheduled.filter(item=>item.type==='BILL_PAYMENT'&&['ACTIVE','PAUSED','RETRY_PENDING'].includes(item.status)&&(isSubscription?item.frequency==='MONTHLY':item.frequency==='ONCE')),[dogaa.scheduled,isSubscription]);
  const resetFields=(code:string)=>{setSelectedCode(code);setReference('');setAmount('');};
  const validate=()=>{const clean=selected?.identifierKind==='DIGITS'?reference.replace(/\D/g,''):reference.trim();const value=Number(amount.replace(/\D/g,''));if(!selected)return null;if(clean.length<selected.minLength||clean.length>selected.maxLength){Alert.alert('Référence invalide',`${selected.identifierLabel} : entre ${selected.minLength} et ${selected.maxLength} caractères.`);return null;}if(value<=0){Alert.alert('Montant invalide','Saisissez un montant supérieur à zéro.');return null;}return {clean,value};};
  const submit=async()=>{const values=validate();if(!values||!selected)return;if(!fundingVaultId){Alert.alert('Coffre requis',`Choisissez le coffre qui paiera ${isSubscription?'cet abonnement':'cette facture'}.`);return;}setSaving(true);try{const monthly=isSubscription&&automatic,firstRun=new Date(`${date}T00:00:00Z`);await schedulingApi.create({type:'BILL_PAYMENT',frequency:monthly?'MONTHLY':'ONCE',amount:values.value,currency:'XOF',beneficiaryReference:values.clean,firstRunAt:firstRun.toISOString(),fundingVaultId,biller:selected.code,dayOfMonth:monthly?firstRun.getUTCDate():undefined});await dogaa.refresh();Alert.alert(isSubscription?'Abonnement enregistré':'Facture enregistrée',monthly?`${selected.displayName} sera payé automatiquement chaque mois depuis le coffre choisi.`:`${selected.displayName} sera payé depuis le coffre choisi à la date indiquée.`);setReference('');setAmount('');}catch(error){Alert.alert('Enregistrement impossible',error instanceof Error?error.message:'Erreur serveur.');}finally{setSaving(false);}};
  return <Screen route={mode} navigate={navigate}>
    <TouchableOpacity onPress={()=>navigate('home')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Accueil</Text></TouchableOpacity>
    <View style={s.head}><View style={s.headIcon}><Ionicons name={isSubscription?'tv-outline':'receipt-outline'} size={27} color={c.yellow}/></View><View style={s.headCopy}><Text style={s.overline}>{isSubscription?'SERVICES RÉCURRENTS':'SERVICES ESSENTIELS'}</Text><Text style={s.title}>{isSubscription?'Mes abonnements':'Enregistrer une facture'}</Text><Text style={s.subtitle}>{isSubscription?'TV, fibre et assurance au Togo.':'Choisissez le coffre qui paiera la facture.'}</Text></View></View>
    <Text style={s.section}>CHOISIR UN SERVICE</Text><View style={s.services}>{services.map(service=><TouchableOpacity key={service.code} onPress={()=>resetFields(service.code)} style={[s.service,selected?.code===service.code&&s.serviceActive]}><Ionicons name={service.code.includes('canal')||service.code.includes('tv')?'tv-outline':service.code.includes('fibre')?'wifi-outline':service.code==='tde'?'water-outline':'flash-outline'} size={21} color={selected?.code===service.code?c.yellow:c.primary}/><Text style={[s.serviceText,selected?.code===service.code&&s.serviceTextActive]}>{service.displayName}</Text></TouchableOpacity>)}</View>
    {selected&&<Card style={s.form}><Text style={s.formTitle}>{selected.displayName}</Text><Text style={s.label}>{selected.identifierLabel.toUpperCase()}</Text><TextInput value={reference} onChangeText={value=>setReference(selected.identifierKind==='DIGITS'?value.replace(/\D/g,''):value)} keyboardType={selected.identifierKind==='DIGITS'?'number-pad':'default'} maxLength={selected.maxLength} placeholder={selected.identifierLabel} placeholderTextColor={c.muted} style={s.input}/><Text style={s.label}>MONTANT</Text><View style={s.amountBox}><TextInput value={amount} onChangeText={value=>setAmount(value.replace(/\D/g,''))} keyboardType="number-pad" placeholder="0" placeholderTextColor={c.muted} style={s.amount}/><Text style={s.currency}>FCFA</Text></View>
      {isSubscription&&<TouchableOpacity onPress={()=>setAutomatic(value=>!value)} style={s.toggle}><Ionicons name={automatic?'checkbox':'square-outline'} size={22} color={automatic?c.greenDark:c.muted}/><View><Text style={s.toggleTitle}>Paiement mensuel automatique</Text><Text style={s.toggleSub}>{automatic?'Répété chaque mois':'Un seul paiement programmé'}</Text></View></TouchableOpacity>}
      <Text style={s.label}>{isSubscription&&automatic?'PREMIÈRE DATE DE PAIEMENT':'DATE DE PAIEMENT'}</Text><DatePickerField value={date} onChange={setDate} placeholder="Choisir une date" minimumDate={new Date()}/><Text style={s.label}>COFFRE QUI EFFECTUERA LE PAIEMENT</Text>{dogaa.vaults.length===0?<View style={s.warning}><Ionicons name="alert-circle-outline" size={18} color={c.yellowDark}/><Text style={s.warningText}>Créez d’abord un coffre DOGAA.</Text></View>:dogaa.vaults.map(vault=><TouchableOpacity key={vault.id} onPress={()=>setFundingVaultId(vault.id)} style={[s.vault,fundingVaultId===vault.id&&s.vaultActive]}><Ionicons name={fundingVaultId===vault.id?'radio-button-on':'radio-button-off'} size={19} color={c.primary}/><Text style={s.vaultText}>{vault.name}</Text><Text style={s.vaultBalance}>{money(Number(vault.balance))} F</Text></TouchableOpacity>)}
      {!isSubscription&&<View style={s.notice}><Ionicons name="information-circle-outline" size={18} color={c.primary}/><Text style={s.noticeText}>La facture sera payée une seule fois, à la date choisie, avec le solde de ce coffre.</Text></View>}
      <TouchableOpacity disabled={saving||dogaa.vaults.length===0} onPress={submit} style={[s.submit,(saving||dogaa.vaults.length===0)&&{opacity:.6}]}><Ionicons name={saving?'hourglass-outline':'calendar-outline'} size={20} color={c.primary}/><Text style={s.submitText}>{saving?'Traitement…':isSubscription?'Enregistrer l’abonnement':'Enregistrer le paiement'}</Text></TouchableOpacity></Card>}
    <><Text style={s.section}>{isSubscription?'ABONNEMENTS':'FACTURES'} ENREGISTRÉ{isSubscription?'S':'ES'} ({saved.length})</Text>{saved.length===0?<Card style={s.empty}><Ionicons name="calendar-outline" size={31} color={c.muted}/><Text style={s.emptyText}>Aucun{isSubscription?' abonnement':'e facture'} enregistré{isSubscription?'':'e'}.</Text></Card>:saved.map(item=><TouchableOpacity key={item.id} disabled={!isSubscription} onPress={()=>onOpenSubscription?.(item.id)}><Card style={s.saved}><View style={s.savedIcon}><Ionicons name={isSubscription?'repeat-outline':'receipt-outline'} size={20} color={c.greenDark}/></View><View style={s.savedCopy}><Text style={s.savedTitle}>{services.find(service=>service.code===item.biller)?.displayName||item.biller||(isSubscription?'Abonnement':'Facture')}</Text><Text style={s.savedSub}>{item.beneficiaryReference} · {item.frequency==='MONTHLY'?'chaque mois':new Date(item.nextRunAt).toLocaleDateString('fr-FR')}</Text></View><Text style={s.savedAmount}>{money(Number(item.amount))} F</Text>{isSubscription&&<Ionicons name="chevron-forward" size={18} color={c.muted}/>}</Card></TouchableOpacity>)}</>
  </Screen>;
}

const s=StyleSheet.create({back:{height:38,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',alignItems:'center',gap:13,marginTop:7},headIcon:{width:56,height:56,borderRadius:18,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},headCopy:{flex:1},overline:{fontSize:8,fontWeight:'900',color:c.greenDark},title:{fontSize:23,fontWeight:'900',color:c.ink,marginTop:2},subtitle:{fontSize:10,color:c.muted,marginTop:3},section:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:22,marginBottom:9},services:{flexDirection:'row',flexWrap:'wrap',gap:8},service:{width:'48%',minHeight:61,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.white,padding:10,flexDirection:'row',alignItems:'center',gap:8},serviceActive:{backgroundColor:c.primary,borderColor:c.primary},serviceText:{fontSize:10,fontWeight:'700',color:c.ink,flex:1},serviceTextActive:{color:c.white},form:{marginTop:15},formTitle:{fontSize:17,fontWeight:'900',color:c.primary},label:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:16,marginBottom:6},input:{height:47,borderRadius:11,borderWidth:1,borderColor:c.border,paddingHorizontal:12,color:c.ink},amountBox:{height:50,borderRadius:11,borderWidth:1,borderColor:c.border,paddingHorizontal:12,flexDirection:'row',alignItems:'center'},amount:{flex:1,fontSize:21,fontWeight:'900',color:c.primary},currency:{fontSize:10,fontWeight:'900',color:c.yellowDark},toggle:{flexDirection:'row',alignItems:'center',gap:9,backgroundColor:c.pale,padding:12,borderRadius:11,marginTop:16},toggleTitle:{fontSize:11,fontWeight:'800',color:c.ink},toggleSub:{fontSize:8,color:c.muted,marginTop:2},vault:{height:43,borderRadius:10,backgroundColor:c.pale,flexDirection:'row',alignItems:'center',paddingHorizontal:10,gap:8,marginBottom:6},vaultActive:{borderWidth:1,borderColor:c.primary},vaultText:{fontSize:10,fontWeight:'700',color:c.ink,flex:1},vaultBalance:{fontSize:9,color:c.muted},warning:{borderRadius:10,backgroundColor:'#FFF4C6',padding:11,flexDirection:'row',gap:8},warningText:{fontSize:9,color:c.yellowDark},notice:{borderRadius:10,backgroundColor:c.pale,padding:11,flexDirection:'row',gap:8,marginTop:15},noticeText:{fontSize:9,lineHeight:14,color:c.muted,flex:1},submit:{height:50,borderRadius:25,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:16},submitText:{fontSize:12,fontWeight:'900',color:c.primary},empty:{alignItems:'center',paddingVertical:23},emptyText:{fontSize:10,color:c.muted,marginTop:7},saved:{marginBottom:8,flexDirection:'row',alignItems:'center',gap:9},savedIcon:{width:39,height:39,borderRadius:20,backgroundColor:'#DDFBED',alignItems:'center',justifyContent:'center'},savedCopy:{flex:1},savedTitle:{fontSize:11,fontWeight:'800',color:c.ink},savedSub:{fontSize:8,color:c.muted,marginTop:3},savedAmount:{fontSize:11,fontWeight:'900',color:c.primary}});
