import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useMemo, useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import DatePickerField from '../components/DatePickerField';
import { Card, Screen } from '../components/Layout';
import { useDogaaData } from '../context/DogaaDataContext';
import { Biller, schedulingApi } from '../services/api';
import { c } from '../theme';
import { Route } from '../types';

const money=(value:number)=>new Intl.NumberFormat('fr-FR').format(value);
const dateValue=(value:string)=>{const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;};

export default function SubscriptionDetailScreen({navigate,subscriptionId}:{navigate:(route:Route)=>void;subscriptionId:string|null}){
  const dogaa=useDogaaData();
  const subscription=useMemo(()=>dogaa.scheduled.find(item=>item.id===subscriptionId),[dogaa.scheduled,subscriptionId]);
  const [offers,setOffers]=useState<Biller[]>([]),[offerCode,setOfferCode]=useState(''),[reference,setReference]=useState(''),[amount,setAmount]=useState(''),[date,setDate]=useState(''),[vaultId,setVaultId]=useState(''),[saving,setSaving]=useState(false);
  useEffect(()=>{schedulingApi.billers().then(setOffers).catch(error=>Alert.alert('Offres indisponibles',error instanceof Error?error.message:'Impossible de charger les offres.'));},[]);
  useEffect(()=>{if(!subscription)return;setOfferCode(subscription.biller||'');setReference(subscription.beneficiaryReference);setAmount(String(Number(subscription.amount)));setDate(dateValue(subscription.nextRunAt));setVaultId(subscription.fundingVaultId||'');},[subscription]);
  const selected=offers.find(item=>item.code===offerCode);
  const save=async()=>{if(!subscription||!selected)return;const clean=selected.identifierKind==='DIGITS'?reference.replace(/\D/g,''):reference.trim(),value=Number(amount.replace(/\D/g,''));if(clean.length<selected.minLength||clean.length>selected.maxLength){Alert.alert('Référence invalide',`${selected.identifierLabel} doit contenir entre ${selected.minLength} et ${selected.maxLength} caractères.`);return;}if(value<=0){Alert.alert('Montant invalide','Saisissez un montant supérieur à zéro.');return;}if(!vaultId){Alert.alert('Coffre requis','Choisissez le coffre qui paiera cet abonnement.');return;}setSaving(true);let replacementId:string|undefined;try{const firstRun=new Date(`${date}T00:00:00Z`);const replacement=await schedulingApi.create({type:'BILL_PAYMENT',frequency:'MONTHLY',amount:value,currency:'XOF',beneficiaryReference:clean,firstRunAt:firstRun.toISOString(),fundingVaultId:vaultId,biller:selected.code,dayOfMonth:firstRun.getUTCDate()});replacementId=replacement.id;await schedulingApi.cancel(subscription.id);await dogaa.refresh();Alert.alert('Abonnement modifié','La nouvelle offre et le coffre de paiement ont bien été enregistrés.',[{text:'Terminé',onPress:()=>navigate('subscriptions')}]);}catch(error){if(replacementId)await schedulingApi.cancel(replacementId).catch(()=>undefined);Alert.alert('Modification impossible',error instanceof Error?error.message:'Erreur serveur.');}finally{setSaving(false);}};
  if(!subscription)return <Screen route="subscriptionDetail" navigate={navigate}><TouchableOpacity onPress={()=>navigate('subscriptions')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Abonnements</Text></TouchableOpacity><Card style={s.empty}><Ionicons name="alert-circle-outline" size={31} color={c.muted}/><Text style={s.emptyText}>Cet abonnement est introuvable.</Text></Card></Screen>;
  return <Screen route="subscriptionDetail" navigate={navigate}>
    <TouchableOpacity onPress={()=>navigate('subscriptions')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Abonnements</Text></TouchableOpacity>
    <View style={s.head}><View style={s.icon}><Ionicons name="tv-outline" size={27} color={c.yellow}/></View><View><Text style={s.overline}>DÉTAILS DE L’ABONNEMENT</Text><Text style={s.title}>Modifier mon offre</Text><Text style={s.subtitle}>Changez l’offre, le coffre ou les informations de paiement.</Text></View></View>
    <Text style={s.section}>CHOISIR UNE OFFRE</Text><View style={s.offers}>{offers.map(offer=><TouchableOpacity key={offer.code} onPress={()=>setOfferCode(offer.code)} style={[s.offer,offerCode===offer.code&&s.offerActive]}><Ionicons name={offer.code.includes('fibre')?'wifi-outline':'tv-outline'} size={20} color={offerCode===offer.code?c.yellow:c.primary}/><Text style={[s.offerText,offerCode===offer.code&&s.offerTextActive]}>{offer.displayName}</Text></TouchableOpacity>)}</View>
    {selected&&<Card style={s.form}><Text style={s.formTitle}>{selected.displayName}</Text><Text style={s.label}>{selected.identifierLabel.toUpperCase()}</Text><TextInput value={reference} onChangeText={value=>setReference(selected.identifierKind==='DIGITS'?value.replace(/\D/g,''):value)} keyboardType={selected.identifierKind==='DIGITS'?'number-pad':'default'} maxLength={selected.maxLength} style={s.input}/><Text style={s.label}>MONTANT MENSUEL</Text><View style={s.amountBox}><TextInput value={amount} onChangeText={value=>setAmount(value.replace(/\D/g,''))} keyboardType="number-pad" style={s.amount}/><Text style={s.currency}>FCFA</Text></View><Text style={s.label}>PROCHAINE DATE DE PAIEMENT</Text><DatePickerField value={date} onChange={setDate} placeholder="Choisir une date" minimumDate={new Date()}/><Text style={s.label}>COFFRE DE PAIEMENT</Text>{dogaa.vaults.map(vault=><TouchableOpacity key={vault.id} onPress={()=>setVaultId(vault.id)} style={[s.vault,vaultId===vault.id&&s.vaultActive]}><Ionicons name={vaultId===vault.id?'radio-button-on':'radio-button-off'} size={19} color={c.primary}/><Text style={s.vaultName}>{vault.name}</Text><Text style={s.balance}>{money(Number(vault.balance))} F</Text></TouchableOpacity>)}<TouchableOpacity disabled={saving||!dogaa.vaults.length} onPress={save} style={[s.submit,(saving||!dogaa.vaults.length)&&{opacity:.6}]}><Ionicons name={saving?'hourglass-outline':'save-outline'} size={20} color={c.primary}/><Text style={s.submitText}>{saving?'Enregistrement…':'Enregistrer les modifications'}</Text></TouchableOpacity></Card>}
  </Screen>;
}

const s=StyleSheet.create({back:{height:38,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',alignItems:'center',gap:13,marginTop:7},icon:{width:56,height:56,borderRadius:18,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},overline:{fontSize:8,fontWeight:'900',color:c.greenDark},title:{fontSize:23,fontWeight:'900',color:c.ink,marginTop:2},subtitle:{fontSize:9,color:c.muted,marginTop:3,maxWidth:260},section:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:22,marginBottom:9},offers:{flexDirection:'row',flexWrap:'wrap',gap:8},offer:{width:'48%',minHeight:58,borderRadius:13,borderWidth:1,borderColor:c.border,backgroundColor:c.white,padding:10,flexDirection:'row',alignItems:'center',gap:8},offerActive:{backgroundColor:c.primary,borderColor:c.primary},offerText:{fontSize:10,fontWeight:'700',color:c.ink,flex:1},offerTextActive:{color:c.white},form:{marginTop:15},formTitle:{fontSize:17,fontWeight:'900',color:c.primary},label:{fontSize:8,fontWeight:'900',color:c.muted,marginTop:16,marginBottom:6},input:{height:47,borderRadius:11,borderWidth:1,borderColor:c.border,paddingHorizontal:12,color:c.ink},amountBox:{height:50,borderRadius:11,borderWidth:1,borderColor:c.border,paddingHorizontal:12,flexDirection:'row',alignItems:'center'},amount:{flex:1,fontSize:21,fontWeight:'900',color:c.primary},currency:{fontSize:10,fontWeight:'900',color:c.yellowDark},vault:{height:46,borderRadius:10,backgroundColor:c.pale,flexDirection:'row',alignItems:'center',paddingHorizontal:10,gap:8,marginBottom:7},vaultActive:{borderWidth:1,borderColor:c.primary},vaultName:{fontSize:10,fontWeight:'700',color:c.ink,flex:1},balance:{fontSize:9,color:c.muted},submit:{height:50,borderRadius:25,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:16},submitText:{fontSize:12,fontWeight:'900',color:c.primary},empty:{alignItems:'center',paddingVertical:25,marginTop:20},emptyText:{fontSize:10,color:c.muted,marginTop:8}});
