import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import React, { useEffect, useMemo, useState } from 'react';
import { Modal, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Card, IconCircle, Screen } from '../components/Layout';
import { c } from '../theme';
import { Route } from '../types';
import { useDogaaData } from '../context/DogaaDataContext';

type Transaction={id:string;title:string;detail:string;date:string;amount:number;kind:'in'|'out';icon:React.ComponentProps<typeof Ionicons>['name'];category:string;status:string};
const base:Transaction[]=[
  {id:'t1',title:'Dépôt client Wave',detail:'Via Agence Treichville',date:"Aujourd’hui, 11:42",amount:50000,kind:'in',icon:'arrow-down-outline',category:'Recharge',status:'Réussie'},
  {id:'t2',title:'Marché Cocody Superette',detail:'Paiement QR marchand',date:'Hier, 19:15',amount:-12500,kind:'out',icon:'qr-code-outline',category:'Paiement',status:'Réussie'},
  {id:'t3',title:'Épargne Scolarité',detail:'Virement programmé vers coffre',date:'10 juin, 08:00',amount:-10000,kind:'out',icon:'lock-closed-outline',category:'Épargne',status:'Réussie'},
  {id:'t4',title:'Maman Adjoua',detail:'Transfert P2P • +225 90 12 34 56',date:'3 juin, 14:28',amount:-20000,kind:'out',icon:'person-outline',category:'Transfert',status:'Réussie'},
  {id:'t5',title:'Remboursement marchand',detail:'Ajustement de paiement',date:'1 juin, 09:05',amount:7500,kind:'in',icon:'return-down-back-outline',category:'Remboursement',status:'Réussie'},
];
const format=(value:number)=>new Intl.NumberFormat('fr-FR').format(Math.abs(value));

export default function TransactionHistoryScreen({navigate}:{navigate:(r:Route)=>void}){
  const dogaa=useDogaaData();
  const [filter,setFilter]=useState<'all'|'in'|'out'>('all');
  const [transactions,setTransactions]=useState(base);
  const [selected,setSelected]=useState<Transaction|null>(null);
  useEffect(()=>{AsyncStorage.getItem('dogaa.wallet.last-recharge').then(raw=>{if(!raw)return;const recharge=JSON.parse(raw) as {provider:string;amount:number};setTransactions(current=>[{id:'latest',title:`Recharge ${recharge.provider}`,detail:'Recharge Mobile Money',date:"Aujourd’hui",amount:recharge.amount,kind:'in',icon:'phone-portrait-outline',category:'Recharge',status:'Réussie'},...current]);}).catch(()=>{});},[]);
  useEffect(()=>{if(!dogaa.loading)setTransactions(dogaa.transactions.map(tx=>{const incoming=['CASH_IN','REFUND','LOAN_DISBURSEMENT'].includes(tx.type);return {id:tx.reference,title:tx.counterparty||tx.description||tx.type,detail:tx.description||tx.type,date:new Date(tx.completedAt||tx.createdAt).toLocaleString('fr-FR'),amount:incoming?Number(tx.amount):-Number(tx.totalDebited||tx.amount),kind:incoming?'in' as const:'out' as const,icon:incoming?'arrow-down-outline' as const:'arrow-up-outline' as const,category:tx.type,status:tx.status};}));},[dogaa.loading,dogaa.transactions]);
  const visible=useMemo(()=>transactions.filter(t=>filter==='all'||t.kind===filter),[transactions,filter]);
  const incoming=transactions.filter(t=>t.amount>0).reduce((sum,t)=>sum+t.amount,0),outgoing=Math.abs(transactions.filter(t=>t.amount<0).reduce((sum,t)=>sum+t.amount,0));
  return <Screen route="transactionHistory" navigate={navigate}>
    <TouchableOpacity onPress={()=>navigate('profile')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Mon profil</Text></TouchableOpacity>
    <View style={s.head}><View><Text style={s.overline}>RELEVÉ DOGAA</Text><Text style={s.title}>Historique des transactions</Text><Text style={s.subtitle}>Toutes les opérations de votre portefeuille.</Text></View><View style={s.headIcon}><Ionicons name="receipt-outline" size={24} color={c.yellow}/></View></View>
    <View style={s.summary}><View style={s.summaryItem}><Ionicons name="arrow-down" size={17} color={c.mint}/><Text style={s.summaryLabel}>ENTRÉES</Text><Text style={s.inAmount}>+{format(incoming)} F</Text></View><View style={s.divider}/><View style={s.summaryItem}><Ionicons name="arrow-up" size={17} color={c.yellow}/><Text style={s.summaryLabel}>SORTIES</Text><Text style={s.outAmount}>-{format(outgoing)} F</Text></View></View>
    <View style={s.filters}>{([['all','Toutes'],['in','Entrées'],['out','Sorties']] as const).map(([key,label])=><TouchableOpacity key={key} onPress={()=>setFilter(key)} style={[s.filter,filter===key&&s.filterActive]}><Text style={[s.filterText,filter===key&&s.filterTextActive]}>{label}</Text></TouchableOpacity>)}</View>
    <Text style={s.period}>TRANSACTIONS RÉCENTES</Text>
    <Card style={s.list}>{visible.map((tx,index)=><TouchableOpacity key={tx.id} onPress={()=>setSelected(tx)} style={[s.tx,index>0&&s.txBorder]}><IconCircle name={tx.icon} bg={tx.kind==='in'?'#DDFBED':c.pale2} color={tx.kind==='in'?c.greenDark:c.primary}/><View style={s.txCopy}><Text style={s.txTitle} numberOfLines={1}>{tx.title}</Text><Text style={s.txDetail} numberOfLines={1}>{tx.detail}</Text><Text style={s.txDate}>{tx.date}</Text></View><View style={s.txRight}><Text style={[s.txAmount,{color:tx.kind==='in'?c.greenDark:c.ink}]}>{tx.kind==='in'?'+':'-'}{format(tx.amount)} F</Text><Ionicons name="chevron-forward" size={15} color={c.muted}/></View></TouchableOpacity>)}</Card>
    <View style={s.secure}><Ionicons name="shield-checkmark-outline" size={17} color={c.greenDark}/><Text style={s.secureText}>Historique sécurisé et disponible à tout moment.</Text></View>
    <Modal transparent visible={!!selected} animationType="slide" onRequestClose={()=>setSelected(null)}><View style={s.overlay}><View style={s.sheet}>{selected&&<><View style={s.sheetHead}><Text style={s.sheetTitle}>Détail de la transaction</Text><TouchableOpacity onPress={()=>setSelected(null)}><Ionicons name="close" size={24}/></TouchableOpacity></View><View style={s.detailIcon}><Ionicons name={selected.icon} size={29} color={c.primary}/></View><Text style={s.detailTitle}>{selected.title}</Text><Text style={[s.detailAmount,{color:selected.kind==='in'?c.greenDark:c.ink}]}>{selected.kind==='in'?'+':'-'}{format(selected.amount)} FCFA</Text><View style={s.detailBox}><Detail label="Type" value={selected.category}/><Detail label="Date" value={selected.date}/><Detail label="Description" value={selected.detail}/><Detail label="Statut" value={selected.status}/><Detail label="Référence" value={`DOGAA-${selected.id.toUpperCase()}-26`} last/></View><TouchableOpacity onPress={()=>setSelected(null)} style={s.closeButton}><Text style={s.closeText}>Fermer</Text></TouchableOpacity></>}</View></View></Modal>
  </Screen>;
}
function Detail({label,value,last=false}:{label:string;value:string;last?:boolean}){return <View style={[s.detailRow,!last&&s.detailBorder]}><Text style={s.detailLabel}>{label}</Text><Text style={s.detailValue}>{value}</Text></View>}
const s=StyleSheet.create({back:{height:36,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:7},overline:{fontSize:8,fontWeight:'800',color:c.greenDark},title:{fontSize:22,lineHeight:28,fontWeight:'900',color:c.ink,maxWidth:270},subtitle:{fontSize:10,color:c.muted,marginTop:3},headIcon:{width:49,height:49,borderRadius:15,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},summary:{backgroundColor:c.primary,borderRadius:14,padding:16,marginTop:17,flexDirection:'row'},summaryItem:{flex:1},summaryLabel:{fontSize:8,fontWeight:'700',color:'#ADC6FF',marginTop:5},inAmount:{fontSize:17,fontWeight:'900',color:c.mint,marginTop:2},outAmount:{fontSize:17,fontWeight:'900',color:c.yellow,marginTop:2},divider:{width:1,backgroundColor:'#FFFFFF22',marginHorizontal:15},filters:{height:42,borderRadius:21,backgroundColor:c.pale2,padding:3,flexDirection:'row',marginTop:17},filter:{flex:1,borderRadius:18,alignItems:'center',justifyContent:'center'},filterActive:{backgroundColor:c.white},filterText:{fontSize:10,color:c.muted},filterTextActive:{fontWeight:'800',color:c.primary},period:{fontSize:8,fontWeight:'800',color:c.muted,marginTop:20,marginBottom:8},list:{paddingVertical:3},tx:{minHeight:75,flexDirection:'row',alignItems:'center',gap:10},txBorder:{borderTopWidth:1,borderTopColor:c.border},txCopy:{flex:1,minWidth:0},txTitle:{fontSize:12,fontWeight:'800',color:c.ink},txDetail:{fontSize:8,color:c.muted,marginTop:2},txDate:{fontSize:8,color:c.muted,marginTop:3},txRight:{alignItems:'flex-end',gap:6},txAmount:{fontSize:11,fontWeight:'900'},secure:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,marginTop:14},secureText:{fontSize:8,color:c.muted},overlay:{flex:1,backgroundColor:'#00235366',justifyContent:'flex-end'},sheet:{backgroundColor:c.white,borderTopLeftRadius:27,borderTopRightRadius:27,padding:22,paddingBottom:34},sheetHead:{flexDirection:'row',justifyContent:'space-between'},sheetTitle:{fontSize:19,fontWeight:'900',color:c.primary},detailIcon:{width:60,height:60,borderRadius:30,backgroundColor:c.pale2,alignItems:'center',justifyContent:'center',alignSelf:'center',marginTop:18},detailTitle:{fontSize:15,fontWeight:'800',color:c.ink,textAlign:'center',marginTop:10},detailAmount:{fontSize:25,fontWeight:'900',textAlign:'center',marginTop:5},detailBox:{backgroundColor:c.pale,borderRadius:11,paddingHorizontal:12,marginVertical:17},detailRow:{minHeight:44,flexDirection:'row',alignItems:'center',gap:10},detailBorder:{borderBottomWidth:1,borderBottomColor:c.border},detailLabel:{fontSize:9,color:c.muted,flex:1},detailValue:{fontSize:9,fontWeight:'700',color:c.ink,textAlign:'right',maxWidth:'58%'},closeButton:{height:48,borderRadius:24,backgroundColor:c.yellow,alignItems:'center',justifyContent:'center'},closeText:{fontSize:12,fontWeight:'900',color:c.primary}});
