import { Ionicons } from '@expo/vector-icons';
import React, { useState } from 'react';
import { Alert, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Card, Progress, Screen } from '../components/Layout';
import { useDogaaData } from '../context/DogaaDataContext';
import { vaultApi } from '../services/api';
import { c } from '../theme';
import { Route } from '../types';

const money=(value:number)=>new Intl.NumberFormat('fr-FR').format(value);
const dateLabel=(value:string)=>new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long',year:'numeric',timeZone:'Africa/Lome'}).format(new Date(value));

export default function VaultDetailScreen({navigate,vaultId}:{navigate:(route:Route)=>void;vaultId:string|null}){
  const dogaa=useDogaaData();
  const vault=dogaa.vaults.find(item=>item.id===vaultId);
  const [open,setOpen]=useState(false),[amount,setAmount]=useState(''),[saving,setSaving]=useState(false);
  if(!vault)return <Screen route="vaultDetail" navigate={navigate}><TouchableOpacity onPress={()=>navigate('vaults')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Mes coffres</Text></TouchableOpacity><Card style={s.missing}><Ionicons name="lock-open-outline" size={38} color={c.muted}/><Text style={s.missingTitle}>Coffre introuvable</Text><Text style={s.missingText}>Revenez à la liste et sélectionnez un coffre.</Text></Card></Screen>;
  const balance=Number(vault.balance),target=Number(vault.targetAmount||0),progress=Number(vault.progressPercent||0);
  const remaining=Math.max(0,target-balance);
  const deposit=async()=>{const value=Number(amount.replace(/\D/g,''));if(value<=0){Alert.alert('Montant invalide','Saisissez un montant supérieur à zéro.');return;}setSaving(true);try{await vaultApi.deposit(vault.id,value);await dogaa.refresh();setAmount('');setOpen(false);Alert.alert('Coffre alimenté',`${money(value)} FCFA ont été ajoutés à ${vault.name}.`);}catch(error){Alert.alert('Versement impossible',error instanceof Error?error.message:'Erreur serveur.');}finally{setSaving(false);}};
  return <Screen route="vaultDetail" navigate={navigate}>
    <TouchableOpacity onPress={()=>navigate('vaults')} style={s.back}><Ionicons name="arrow-back" size={19} color={c.primary}/><Text style={s.backText}>Mes coffres</Text></TouchableOpacity>
    <View style={s.head}><View style={s.lock}><Ionicons name="lock-closed-outline" size={27} color={c.yellow}/></View><View style={s.headCopy}><Text style={s.overline}>COFFRE DOGAA</Text><Text style={s.title}>{vault.name}</Text><Text style={s.description}>{vault.description||'Votre épargne sécurisée.'}</Text></View></View>
    <Card style={s.balanceCard}><Text style={s.balanceLabel}>SOLDE DU COFFRE</Text><Text style={s.balance}>{money(balance)} <Text style={s.fcfa}>FCFA</Text></Text><View style={s.progressHead}><Text style={s.progressText}>Progression de l’objectif</Text><Text style={s.percent}>{Math.round(progress)}%</Text></View><Progress value={progress} color={c.yellow}/><View style={s.goalRow}><Text style={s.goal}>Objectif : {target?`${money(target)} FCFA`:'Non défini'}</Text>{target>0&&<Text style={s.remaining}>Reste {money(remaining)} FCFA</Text>}</View></Card>
    <View style={s.infoGrid}><Info icon="calendar-outline" label="DATE CIBLE" value={vault.targetDate?dateLabel(vault.targetDate):'Non définie'}/><Info icon="shield-checkmark-outline" label="STATUT" value={vault.status}/></View>
    <Card style={s.details}><Row label="Créé le" value={dateLabel(vault.createdAt)}/><Row label="Devise" value={vault.currency}/><Row label="Identifiant" value={vault.id.slice(0,8).toUpperCase()} last/></Card>
    <TouchableOpacity onPress={()=>setOpen(true)} style={s.deposit}><Ionicons name="add-circle-outline" size={21} color={c.primary}/><Text style={s.depositText}>Alimenter ce coffre</Text></TouchableOpacity>
    <Modal transparent visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={s.sheet}><View style={s.sheetHead}><View><Text style={s.sheetTitle}>Alimenter {vault.name}</Text><Text style={s.sheetSub}>Les fonds seront transférés depuis votre portefeuille.</Text></View><TouchableOpacity onPress={()=>setOpen(false)}><Ionicons name="close" size={24} color={c.ink}/></TouchableOpacity></View><Text style={s.formLabel}>MONTANT EN FCFA</Text><View style={s.amountField}><TextInput autoFocus value={amount} onChangeText={value=>setAmount(value.replace(/\D/g,''))} placeholder="0" placeholderTextColor={c.muted} keyboardType="number-pad" style={s.input}/><Text style={s.currency}>FCFA</Text></View><TouchableOpacity disabled={saving} onPress={deposit} style={[s.deposit,saving&&{opacity:.6}]}><Ionicons name={saving?'hourglass-outline':'checkmark-circle-outline'} size={21} color={c.primary}/><Text style={s.depositText}>{saving?'Versement…':'Confirmer le versement'}</Text></TouchableOpacity></View></View></Modal>
  </Screen>;
}

function Info({icon,label,value}:{icon:React.ComponentProps<typeof Ionicons>['name'];label:string;value:string}){return <Card style={s.infoCard}><Ionicons name={icon} size={20} color={c.greenDark}/><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value}</Text></Card>}
function Row({label,value,last=false}:{label:string;value:string;last?:boolean}){return <View style={[s.row,!last&&s.rowBorder]}><Text style={s.rowLabel}>{label}</Text><Text style={s.rowValue}>{value}</Text></View>}

const s=StyleSheet.create({back:{height:38,alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:11,fontWeight:'700',color:c.primary},head:{flexDirection:'row',alignItems:'center',gap:13,marginTop:8},lock:{width:58,height:58,borderRadius:18,backgroundColor:c.primary,alignItems:'center',justifyContent:'center'},headCopy:{flex:1},overline:{fontSize:8,fontWeight:'800',color:c.greenDark},title:{fontSize:23,fontWeight:'900',color:c.ink,marginTop:2},description:{fontSize:10,color:c.muted,marginTop:3},balanceCard:{backgroundColor:c.primary,marginTop:20,padding:20},balanceLabel:{fontSize:9,fontWeight:'800',color:'#ADC6FF'},balance:{fontSize:30,fontWeight:'900',color:c.yellow,marginTop:7},fcfa:{fontSize:15,color:c.white},progressHead:{flexDirection:'row',justifyContent:'space-between',marginTop:22,marginBottom:9},progressText:{fontSize:10,color:c.white},percent:{fontSize:11,fontWeight:'900',color:c.yellow},goalRow:{flexDirection:'row',justifyContent:'space-between',marginTop:9,gap:8},goal:{fontSize:9,color:'#DCE4FF'},remaining:{fontSize:9,fontWeight:'700',color:c.mint},infoGrid:{flexDirection:'row',gap:10,marginTop:13},infoCard:{flex:1,minHeight:105},infoLabel:{fontSize:8,fontWeight:'800',color:c.muted,marginTop:10},infoValue:{fontSize:11,fontWeight:'800',color:c.ink,marginTop:4},details:{marginTop:13,paddingVertical:3},row:{minHeight:47,flexDirection:'row',alignItems:'center'},rowBorder:{borderBottomWidth:1,borderBottomColor:c.border},rowLabel:{fontSize:10,color:c.muted,flex:1},rowValue:{fontSize:10,fontWeight:'800',color:c.ink},deposit:{height:52,borderRadius:26,backgroundColor:c.yellow,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,marginTop:16},depositText:{fontSize:13,fontWeight:'900',color:c.primary},missing:{alignItems:'center',paddingVertical:35,marginTop:20},missingTitle:{fontSize:16,fontWeight:'800',color:c.ink,marginTop:10},missingText:{fontSize:10,color:c.muted,marginTop:4},overlay:{flex:1,backgroundColor:'#00235366',justifyContent:'flex-end'},sheet:{backgroundColor:c.white,borderTopLeftRadius:27,borderTopRightRadius:27,padding:22,paddingBottom:35},sheetHead:{flexDirection:'row',justifyContent:'space-between',gap:12},sheetTitle:{fontSize:19,fontWeight:'900',color:c.primary},sheetSub:{fontSize:10,color:c.muted,marginTop:4},formLabel:{fontSize:9,fontWeight:'800',color:c.muted,marginTop:22,marginBottom:7},amountField:{height:52,borderWidth:1,borderColor:c.border,borderRadius:12,paddingHorizontal:13,flexDirection:'row',alignItems:'center'},input:{flex:1,fontSize:22,fontWeight:'800',color:c.primary},currency:{fontSize:11,fontWeight:'800',color:c.yellowDark}});
