name: CI/CD Backend Spring Boot

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**' # S'enclenche uniquement si tu modifies le dossier backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer le JDK 21 (ou ta version de Java)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven' # ou 'gradle' selon ton projet

    - name: Compiler et lancer les tests
      run: |
        cd backend
        mvn clean test

    - name: Packager l'application (JAR)
      if: success()
      run: |
        cd backend
        mvn package -DskipTests