name: CI/CD Backend Spring Boot

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupération du code depuis ton dépôt GitHub
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

    # 2. Configuration de l'environnement Java (JDK 17)
    - name: Set up Java
      uses: actions/setup-java@3a47288d07f9a1a665079c8bf28d3ee0870ddfad
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # 3. Compilation et packaging en ignorant le test de contexte de base de données
    - name: Compiler et packager l'application (JAR)
      run: |
        cd backend
        mvn clean package -DskipTests