name: CI Mobile React Native

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'

jobs:
  test-mobile:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Configurer Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'mobile/package-lock.json'

    - name: Installer les dépendances
      run: |
        cd mobile
        npm ci

    - name: Lancer les tests unitaires (Jest)
      run: |
        cd mobile
        npm run test --if-present