name: CI Mobile Flutter

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mobile/**'

jobs:
  test-mobile:
    runs-on: ubuntu-latest

    steps:
    # Remplacez les lignes 15 et 18 :
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Flutter
      uses: subosito/flutter-action@f2c35ec8b297f45b847af0400570b555e5108dc8 # v2.18.0
      with:
        flutter-version: '3.44.2'
        channel: 'stable'
        cache: true

    - name: Installer les dépendances
      run: |
        cd mobile
        flutter pub get

    - name: Vérifier le formatage du code
      run: |
        cd mobile
        dart format --output=none --set-exit-if-changed .

    - name: Analyser le code (lints)
      run: |
        cd mobile
        flutter analyze

    - name: Lancer les tests unitaires
      run: |
        cd mobile
        flutter test --coverage